# enable debug mode
debug: true

# port
port: 8080

# mysql data source
db_source: "root:wang182764@/"

# email domain name
domain_name: "mkideal.com"

max_session_size: 8096

service_info: "Service ready"
